### ISSUE TITLE
Show the meetup-faqs

### ISSUE THREAD

**Issue by RobChooses** [freeCodeCampLondon/fcc-website#21]
Create a page to show the faqs from the https://github.com/freeCodeCampLondon/meetup-faq repo.

Maybe move the FAQs to this repo?

**Comment by SeanAverS** [comment]
Hello, 

I'm interested on working on this. Could I please be assigned? Thanks.

**Comment by RobChooses** [comment]
Assigned @SeanAverS !

**Comment by RobChooses** [comment]
Actually @deej-tsn already started on the About page which had most of this content, so this issue can be closed.
